baseURL = 'http://newdegeneration.xyz/'
languageCode = 'en-us'
title = 'Portfolio - Nikola Stoyanov'
copyright = "Nikola Soyanov, 2023"
Description = "Personal Porfolio of Nikola Stoyanov"

[Author]
    name = "Nikola Stoyanov"
    email = "av0id.biz@gmail.com"

[sitemap]
  filename = "sitemap.xml"
  enableRobotsTXT = false

[markup]
  defaultMarkdownHandler = 'goldmark'

[taxonomies]
category = "categories"

[minify]
  disableXML = false

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

