baseURL = 'https://newdegeneration.xyz'
languageCode = 'en-us'
copyright_url = "/tech-spec/tech-spec/"

[sitemap]
  filename = "sitemap.xml"
  enableRobotsTXT = true
  changeFreq = "daily"
  image = false

[markup]
  defaultMarkdownHandler = 'goldmark'

[taxonomies]
  category = "categories"

# I disabled this in the netlify.toml because it was leading to escaping characters in the schema lists
# [minify]
#   disableXML = true

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    disabled = false
    title = "Nikola Stoyanov"
    weight = "1"
    [languages.en.params]
      Description = "Nikola Stoyanov is a contemporary visual artist and machine philosopher from Varna, Bulgaria."
      name = "Nikola Stoyanov"
      alternateName = "Nikola Vladislavov Stoyanov"
      jobTitle = "Artist and philosopher"
      profileImage = "images/profile.jpg"
      sameAs = [
        "https://www.facebook.com/av0id.nd/",
        "https://www.instagram.com/avoid.nd/",
        "https://www.linkedin.com/in/nstoyanov23/",
        "https://twitter.com/new_degen",
        "https://www.youtube.com/@newdegeneration",
        "https://www.wikidata.org/wiki/Q124417026",
        "https://www.goodreads.com/author/show/48653203._",
        "https://www.imdb.com/name/nm16814810"
      ]
      organizerUrl = "https://newdegeneration.xyz/bio/"
      performerUrl = "https://newdegeneration.xyz/bio/"
    [[languages.en.menu.main]]
      url = "/work/"
      name = "work"
      weight = 1
    [[languages.en.menu.main]]
      url = "/bio/"
      name = "bio"
      weight = 2
    [[languages.en.menu.main]]
      url = "https://blog.newdegeneration.xyz/"
      name = "blog"
      weight = 3

  [languages.bg]
    languageName = "Български"
    disabled = false
    weight = "2"
    title = "Никола Стоянов"
    [languages.bg.params]
      Description = "Никола Стоянов е съвременен визуален артист и машинен философ от Варна, България."
      name = "Никола Стоянов"
      alternateName = "Никола Владиславов Стоянов"
      jobTitle = "Визуален артист и философ"
      profileImage = "images/profile.jpg"
      sameAs = [
        "https://www.facebook.com/av0id.nd/",
        "https://www.instagram.com/avoid.nd/",
        "https://www.linkedin.com/in/nstoyanov23/",
        "https://twitter.com/new_degen",
        "https://www.youtube.com/@newdegeneration",
        "https://www.wikidata.org/wiki/Q124417026",
        "https://www.goodreads.com/author/show/48653203._",
        "https://www.imdb.com/name/nm16814810"
      ]
      organizerUrl = "https://newdegeneration.xyz/bio/"
      performerUrl = "https://newdegeneration.xyz/bio/"
    [[languages.bg.menu.main]]
      url = "/bg/work/"
      name = "труд"
      weight = 1
    [[languages.bg.menu.main]]
      url = "/bg/bio/"
      name = "био"
      weight = 2
    [[languages.bg.menu.main]]
      url = "https://blog.newdegeneration.xyz/"
      name = "блог"
      weight = 3
