baseURL = 'https://newdegeneration.xyz'
languageCode = 'en-us'
copyright_url = "/tech-spec/tech-spec/"

[sitemap]
  filename = "sitemap.xml"
  enableRobotsTXT = true
  changeFreq = "daily"
  image = false

[markup]
  defaultMarkdownHandler = 'goldmark'

[taxonomies]
category = "categories"

[minify]
  disableXML = true

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    disabled = false
    title = 'Nikola Stoyanov'
    weight = "1"
      [languages.en.params]
      Description = "Nikola Stoyanov is a visual artist and machine philosopher hailing from Varna, Bulgaria."
      [[languages.en.menu.main]]
      url    = "/work/"
      name   = "work"
      weight = 1
      [[languages.en.menu.main]]
      url    = "/bio/"
      name   = "bio"
      weight = 2
      [[languages.en.menu.main]]
      url    = "https://blog.newdegeneration.xyz/"
      name   = "blog"
      weight = 3

  [languages.bg]
    languageName = "Български"
    disabled = false
    weight = "2"
    title = 'Никола Стоянов'
      [languages.bg.params]
      Description = "Никола Стоянов е визуален артист и машинен философ от Варна, България."
      [[languages.bg.menu.main]]
      url    = "/bg/work/"
      name   = "труд"
      weight = 1
      [[languages.bg.menu.main]]
      url    = "/bg/bio/"
      name   = "био"
      weight = 2
      [[languages.bg.menu.main]]
      url    = "https://blog.newdegeneration.xyz/"
      name   = "блог"
      weight = 3
    
