baseURL = '/'
languageCode = 'en-us'
title = 'Nikola Stoyanov'
copyright = "Nikola Soyanov, 2023"
Description = "Personal Porfolio of Nikola Stoyanov"

[Author]
    name = "Nikola Stoyanov"
    email = "av0id.biz@gmail.com"

[sitemap]
  filename = "sitemap.xml"
  enableRobotsTXT = true

[markup]
  defaultMarkdownHandler = 'goldmark'

[taxonomies]
category = "categories"

[minify]
  disableXML = false

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

[imageProcessing]
  resampleFilter = "lanczos"
  anchor = "smart"

  [outputFormats.imagessitemap]
  baseName  = 'imagessitemap'
  mediaType = 'application/xml'
  noUgly = true # default is false

  [outputs]
  page = [ "html"]
  home = [ "html", "rss", "imagessitemap"]