baseURL = "https://newdegeneration.xyz"
languageCode = "en-us"
copyright_url = "/tech-spec/tech-spec/"

[sitemap]
  filename = "sitemap.xml"
  enableRobotsTXT = true
  changeFreq = "weekly"

[markup]
  defaultMarkdownHandler = "goldmark"

[taxonomies]
  category = "categories"

[minify]
  disableXML = true

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Nikola Stoyanov"
    weight = 1

    [languages.en.params]
      Description = "Personal Porfolio of Nikola Stoyanov"

    [[languages.en.menu.main]]
      url    = "/work/"
      name   = "work"
      weight = 1

    [[languages.en.menu.main]]
      url    = "/bio/"
      name   = "bio"
      weight = 2

    [[languages.en.menu.main]]
      url    = "https://blog.newdegeneration.xyz/"
      name   = "blog"
      weight = 3

  [languages.bg]
    languageName = "Български"
    title = "Никола Стоянов"
    weight = 2

    [languages.bg.params]
      Description = "Портфолио Никола Стоянов"

    [[languages.bg.menu.main]]
      url    = "/bg/work/"
      name   = "проекти"
      weight = 1

    [[languages.bg.menu.main]]
      url    = "/bg/bio/"
      name   = "биография"
      weight = 2

    [[languages.bg.menu.main]]
      url    = "https://blog.newdegeneration.xyz/"
      name   = "блог"
      weight = 3



[outputFormats]
  [outputFormats.ImageSitemap]
    name = "imagesitemap"
    mediaType = "application/xml"
    isHTML = false
    baseName = "imagesitemap"

[outputs]
  section = ["HTML", "RSS", "ImageSitemap"]
