baseURL = 'http://newdegeneration.xyz/'
languageCode = 'en-us'
title = 'Nikola Stoyanov'
copyright = "Nikola Soyanov, 2023"

[Author]
    name = "Nikola Stoyanov"
    email = "av0id.biz@gmail.com"

 Description = "Personal Porfolio of Nikola Stoyanov"

[sitemap]
  filename = "sitemap.xml"
  enableRobotsTXT = true

[markup]
  defaultMarkdownHandler = 'goldmark'

[taxonomies]
category = "categories"

[minify]
  disableXML = false


