baseURL = 'http://newdegeneration.xyz/'
languageCode = 'en-us'
title = 'Nikola Stoyanov'
copyright = "Nikola Soyanov, 2023"

[Author]
    name = "Nikola Stoyanov"
    email = "av0id.biz@gmail.com"

 Description = "A translator and photographer for many years, he enjoys interweaving the human- ities with the scientific, multi-linear approaches to problem solving and collaborative work."

enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[robots]

[blackfriday]
  extensions = ["hardLineBreak"]

[taxonomies]
category = "categories"