[build]
  command = "hugo --minify"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.119.0"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/unsound-hikikomori/"
  to = "https://blog.newdegeneration.xyz/unsound-hikikomori"
  status = 301
  force = true
